### ISSUE TITLE
Tmux automatically rename windows

### ISSUE THREAD

**Issue by haruops** [craftzdog/dotfiles-public#105]
I assume you mean you don't want tmux to automatically rename?

This line should be in your tmux.conf,`set-option -g automatic-rename off` However, this should be the default setting. Make sure you didn't copy over this option from another conf.

_Originally posted by @igniscyan in https://github.com/craftzdog/dotfiles-public/issues/99#issuecomment-1422876670_

**Comment by igniscyan** [comment]
> All default tmux settings.
> 
You have status line enabled and styled, you may not realize it but this is not a default tmux configuration.

**Comment by haruops** [comment]
> Did you use the configuration line I sent you?

Yes, but it didn't help.

>You have status line enabled and styled, you may not realize it but this is not a default tmux configuration.
Default by @craftzdog

**Comment by haruops** [comment]
I was told that the problem is in the following code.  But how do I fix it?

>Your `window-status-format` is configured to show `pane_current_path` in the status line, so it will change every time you change directory:

>`1679056254.662709 cmdq_fire_command <global>: (2836) set-window-option -g window-status-format "#[fg=#002b36,bg=#002b36]\356\202\260#[default] #I \356\202\261 #{b:pane_current_path} #[fg=#002b36,bg=#002b36,nobold,nounderscore,noitalics]\356\202\260"`
