### ISSUE TITLE
Issue with treesitter/highlighter n lua scripts

### ISSUE THREAD

**Issue by mPanasiewicz** [craftzdog/dotfiles-public#109]
I noticed that the lua parser raises an error(picture below). It seems that's the newest version of treesitter conflicts with neovim 0.8.X . The only soulution what I found is to bump the version of your neovim to `nightly` which is `0.9.0` right now.
[Source](https://github.com/LunarVim/LunarVim/issues/3680#issuecomment-1374025577)

PS: The guide explained in the above link didn't solved the issue. Neovim upgrade did the job
![image](https://user-images.githubusercontent.com/9081428/222698448-432c65d5-ae74-41ca-babb-00586f492257.png)

**Comment by PowerzinBR** [comment]
Well, if you can use the Neovim without errors, than just ignore it? 🐑
