### ISSUE TITLE
My theme doesn't have a git status prompt

### ISSUE THREAD

**Issue by nuo-promise** [craftzdog/dotfiles-public#11]
<img width="962" alt="iShot2021-08-22 23 05 20" src="https://user-images.githubusercontent.com/46160170/130360073-4fae88d5-b9e3-4fe0-b0d3-09bbef42a9c7.png">

**Comment by nuo-promise** [comment]
Can you tell me when you write the program to use the shortcut keys to operate the document, there is a tutorial link can provide under it @craftzdog

**Comment by craftzdog** [comment]
You can ask it on the tide community https://github.com/IlanCosman/tide
