### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by woylesniak** [craftzdog/dotfiles-public#12]
Could you explain the exact configuration of the icons ? They show up all the time [?]

**Comment by DemoorBug** [comment]
[Hack Nerd Font.zip](https://github.com/craftzdog/dotfiles-public/files/7113253/Hack.Nerd.Font.zip) This is the font I patched

[Patch Your Own Font](https://github.com/ryanoasis/nerd-fonts#font-patcher)

**Comment by h123a456rr789y** [comment]
Hi,
could you also explain how we can get the font icons for the exa command? 
I saw the .js and .coffee files were in some really nice icons!
Thanks!
