### ISSUE TITLE
Need help regarding peco in fish shell

### ISSUE THREAD

**Issue by harshv1741** [craftzdog/dotfiles-public#122]
![image](https://github.com/craftzdog/dotfiles-public/assets/51878195/bdce644f-93fd-42d8-a146-7b3502883122)

I was trying to use the ctrl + f shortcut created by Takuya, but I don't know how to install peco in wsl. I tried it installing using fisher, but it is still not working. Could anyone help me as to how I can install required files for using  ctrl + f shortcut ?

**Comment by kumamiko** [comment]
https://github.com/peco/peco

if your system have apt, just 
```sh
apt install peco
```

**Comment by harshv1741** [comment]
@kumamiko I'm using openSUSE-Tumbleweed so does zypper package manager contains peco

**Comment by kumamiko** [comment]
> @kumamiko I'm using openSUSE-Tumbleweed so does zypper package manager contains peco
> 

I haven't use zypper. You can have a try. If zypper does not have peco. You can download peco from it's github release page.

**Comment by harshv1741** [comment]
Update Regarding this issue,
