### ISSUE TITLE
TSserver configuration

### ISSUE THREAD

**Issue by Shaurya699** [craftzdog/dotfiles-public#125]
Here in lspconfig.rc.lua 

after writing this piece of code I get this error everytime

nvim_lsp.tssever.setup {
	on_attach = on_attach,
	filetypes = { "typescript", "typescriptreact", "typescript.tsx" },
	cmd = { "typescript-language-server", "--stdio" },
	capabilities = capabilities
}

**Comment by jamkich** [comment]
hi, can u send an error u got?

**Comment by Shaurya699** [comment]
Sorry for not sending the error but I got the answer thank you for giving me help.
