### ISSUE TITLE
tmux: change terminal color

### ISSUE THREAD

**Issue by haruops** [craftzdog/dotfiles-public#129]
How can I set the same text color in tmux as in my standard terminal?
Thanks.

![SCR-20230704-nrv](https://github.com/craftzdog/dotfiles-public/assets/44260786/0c58a092-a505-420d-9ffc-88bf74865f66)

**Comment by craftzdog** [comment]
Configure the color palette correctly like so:

<img width="812" alt="Screenshot 2023-08-08 at 10 52 46" src="https://github.com/craftzdog/dotfiles-public/assets/1332805/aefb5fa7-c58c-477b-a09f-2faa8e398280">
