### ISSUE TITLE
Alternative for null-ls

### ISSUE THREAD

**Issue by CofCat456** [craftzdog/dotfiles-public#132]
Hi Takuya !

Recently, the author of `null-ls` announced that they will [stop maintaining the plugin](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621#issuecomment-1675044379), and it was archived today..

 I'm wondering if you're considering using other plugins to replace `null-ls`? I've seen suggestions to use formatters like [neoformat](https://github.com/sbdchd/neoformat) or [formatter](https://github.com/mhartington/formatter.nvim) for code formatting, As for eslint, [Lsp Eslint](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint) might be a good option.

Take care and rest well. If you need it, I'll keep an eye on updates in this area and hope to assist you!

**Comment by craftzdog** [comment]
yeah I'm aware of that - will look into them

**Comment by Lamarcke** [comment]
I'm currently using `nvim-lint` and `formatter.nvim` to achieve the same result.
My formatter.nvim config:
```lua
return {
    "mhartington/formatter.nvim",
    config = function()
        local formatter = require("formatter")
        local default_formatters = require("formatter.defaults")
        local prettierd = default_formatters.prettierd
        local stylua = default_formatters.stylua
        formatter.setup({
            filetype = {
                javascript = {
                    prettierd
                },
                javascriptreact = {
                    prettierd
                },
                typescript = {
                    prettierd
                },
                typescriptreact = {
                    prettierd
                },
                lua = {
                    stylua
                }
            }

        })
    end
}

```

My nvim-lint config:
```lua
return {
    "mfussenegger/nvim-lint",
    config = function()
        local lint = require("lint")
        lint.linters_by_ft = {
            javascript = {
                "eslint_d"
            },
            typescript = {
                "eslint_d"
            },
            javascriptreact = {
                "eslint_d"
            },
            typescriptreact = {
                "eslint_d"
            }
        }

        -- Autocommand for nvim-lint
        vim.api.nvim_create_autocmd({ "InsertLeave", "BufWritePost" }, {
            callback = function()
                  lint.try_lint()
            end,
        })

    end

}
```

You should then use `:h vim.diagnostic.config` to change how diagnostics are displayed.

Both plugins are standalone, so no dependency on external binaries like the efm language server.

**Comment by kuzyo** [comment]
Looks like null_ls is going to be picked by community and developed under this project - https://github.com/nvimtools/none-ls.nvim

**Comment by craftzdog** [comment]
yep, that's great news!
I'm planning to make another video on my recent setup (maybe next month)
let me close this for now

**Comment by kuzyo** [comment]
Eager to check on your new theme 🚀.

**Comment by harshv5094** [comment]
> yep, that's great news! I'm planning to make another video on my recent setup (maybe next month) let me close this for now
We are very exited to see your new setup.
