### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by luanargolodev** [craftzdog/dotfiles-public#136]
Hey guys!
How do I configure the terminal to stay the same?

I was doing it according to this tutorial (https://www.youtube.com/watch?v=RNqDkF17ogY) but at 6:43 it skips and the terminal is already configured.

Can someone help me?

**Comment by fvrrrn** [comment]
Not sure what do you mean by 'stay the same', I'm going to assume you want the same terminal shell as in the given video. If so, check out Takuya's terminal shell configuration [here](https://youtu.be/KKxhf50FIPI).

**Comment by GeoffreyBrunet** [comment]
It's the same terminal with tmux open and fish shell with custom prompt.

**Comment by cattynip** [comment]
If you want to configure the terminal, then you can simply type `tide configure` on the terminal. This only works when you have installed the fisher plugin, `tide`, obviously. To install `tide`, you can type `fisher install IlanCosman/tide@v6`. *DO NOT FORGET TO RUN ALL THESE COMMANDS ON FISH SHELL!*
