### ISSUE TITLE
Disable NeoTree if not used

### ISSUE THREAD

**Issue by Pkcarreno** [craftzdog/dotfiles-public#143]
Hi, Thanks for this amazing and inspiring config

I just noticed NeoTree plugin is still enabled, I think if you are using Telescope file browser to explore files maybe disabling NeoTree could be useful (I don't know about the actual impact on startup time, I think it's null but at least it free some key bindings)

```lua
return {
  -- disable NeoTree
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
}
```

**Comment by craftzdog** [comment]
It isn't necessary as NeoTree will not be loaded until you run the command `Neotree` because of the `cmd` option in LazyVim:

```lua
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    cmd = "Neotree",
```

I'd like to keep my config minimal.
If I'm wrong, please let me know
