### ISSUE TITLE
Can't see the color highlights for css in`hsl()`

### ISSUE THREAD

**Issue by harshv5094** [craftzdog/dotfiles-public#147]
![image](https://github.com/craftzdog/dotfiles-public/assets/51878195/a84be666-3b57-4215-9f98-7050eb6f3f0f)
I'm using debian wsl, in windows terminal. But I can't see color highlight in `hsl()`. Can someone help me to fix this issue.

**Comment by harshv5094** [comment]
@craftzdog can you please check my issue here.

**Comment by PowerzinBR** [comment]
Maybe reinstall Neovim or use a recent configuration?
This is probably to a bug.
