### ISSUE TITLE
error the nvim telescope config

### ISSUE THREAD

**Issue by iafshinafshin** [craftzdog/dotfiles-public#148]
my error in config telescope plugin.
i use your config nvim : **nvim/lua/plugins/editor.lua**  and  my system is  _ubuntu 22.04.3_ 
my error at this image and not show my files and i use **sf** and in show mee the error message : 
![Screenshot from 2023-12-14 23-20-24](https://github.com/craftzdog/dotfiles-public/assets/138600371/10d92ea9-26a3-4bfb-870d-c801b750cae9)

**THIS IS MY PROBLEM**

**Comment by stormespace** [comment]
did you install ripgrep

**Comment by Afshinafshi** [comment]
yes, i install ripgrep and my ripgrep version is 12.1.0

**Comment by iafshinafshin** [comment]
I change system and fixed problem
