### ISSUE TITLE
how to add new plugins of our own?

### ISSUE THREAD

**Issue by adilzaheem** [craftzdog/dotfiles-public#155]
can somebody help me to add a plugin of my choice to this ?

**Comment by mahesh-143** [comment]
@adilzaheem Did you mean neovim plugin or fish plugin ?

If you want to add nvim plugin then in `nvim/lua/plugins/` create a lua file and return your plugin like this 

```lua
return {
"githubuname/pluginname"
}
""
}
```
Check out LazyVim's docs for adding plugin for more info about adding opts, keys etc. 
Also check the github readme of the plugin you want to add.
