### ISSUE TITLE
Lightweight-feeling version

### ISSUE THREAD

**Issue by PowerzinBR** [craftzdog/dotfiles-public#160]
Hey Takuya! Hope you're good.
In your recent version of LazyVim, i personaly didn't expect that it not meet my "expectatives", and i created a **lightweight-feeling** version of your setup, it includes some plugins you use, your colorscheme and some codes from this repository (.config/nvim).

And probably i may know that my pc is bad and it can be very laggy, but i don't remember a laggy version of any Neovim distro (Like AstroNvim)
And i wanted your answer, could i make a repository about the Neovim configuration, giving credits to you? I hope you're good, waiting your answer!

![image](https://github.com/craftzdog/dotfiles-public/assets/140966320/7bb5f1bf-32a2-4c66-adbe-3ad258a9c648)

![image](https://github.com/craftzdog/dotfiles-public/assets/140966320/37bd6f33-4564-4237-a062-1945e7e164f3)

Cheers!

**Comment by PowerzinBR** [comment]
@craftzdog Could you see this? :)

**Comment by craftzdog** [comment]
Completely fine.
