### ISSUE TITLE
Help: How can I bring back open any file on new buffer default behavior in lazyvim?

### ISSUE THREAD

**Issue by harshv5094** [craftzdog/dotfiles-public#163]
Hey, I want to open everyfile on new tab in bufferline plugin so can anyone tell me how I can do it?

**Comment by PowerzinBR** [comment]
Hm, you mean like:

- launch neovim
- launch automatically a tab in the selected file

If that's the case, i think we can't do it

**Comment by harshv5094** [comment]
But in lazyvim starter config, Everytime I open a file the files open in a
new buffer in seperate tab just like vscode so I know that it is possible.
It's just that I'm unable to find how to do that

**Comment by PowerzinBR** [comment]
Oh, i see. Maybe try to check files in ui.lua? I think the bufferline config is there

**Comment by harshv5094** [comment]
Found It! Just needed to remove Buffeline Config

**Comment by harshv5094** [comment]
It changes it to its default behavior

**Comment by harshv5094** [comment]
![image](https://github.com/craftzdog/dotfiles-public/assets/51878195/193cab42-d3f0-46db-890b-0dc06fa38a2e)
Just did this and I'm set
