### ISSUE TITLE
classname being selected

### ISSUE THREAD

**Issue by krishna-paulraj** [craftzdog/dotfiles-public#173]
My nvim acting weird today..

When I move the closing div to next line its not alined properly

Classnames being auto selected while writing em🥲
colors preview not showing up due to this issue

https://github.com/user-attachments/assets/4d8daa9c-c118-4e27-bf37-e5a06a54b889

**Comment by HamzaVim** [comment]
Me too, I have the same issue: Classnames being auto-selected while writing

**Comment by craftzdog** [comment]
can't reproduce it
