### ISSUE TITLE
Problem with searching file contents

### ISSUE THREAD

**Issue by musicaljoeker** [craftzdog/dotfiles-public#2]
Hello, I love your dotfiles and YouTube videos demoing your workflow. I've worked to improve my workflow by incorporating some of them.

In your Denite configuration file you have this line of code:
https://github.com/craftzdog/dotfiles-public/blob/6f415824dbf8637a391cab29e470399880a3e834/.config/nvim/plugins/denite.rc.vim#L44

Which as I understand shows the "lambda" search box to filter the popup window. This works OK for the `;f` keystrokes to search filenames but when I want to grep file contents (`;r`) using the `Dgrep` function, I receive an error as follows:

```
[denite] option "-start_filter=": type is invalid.
Pattern:
```

I can then search by pattern, but can no longer filter after searching. I am wondering if you've seen this before? Perhaps a Denite version incompatibility with the dotfiles and a newer version? I'm not sure.

I have tried substituting `v:true` with `1` (which did not work). I'm curious if you have any other suggestions.

Thank you in advance.

**Comment by DemoorBug** [comment]
`;r` live grep does not work you can try to install this library https://github.com/BurntSushi/ripgrep

**Comment by Adham2023** [comment]
I also faced to this problem but with this "Suggested dependencies
[BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) is required for live_grep and grep_string" I did not install dependecies correctly

**Comment by fixbullshit14** [comment]
would u help me 

share_with_app_devs":0,"app_version":"","bug_type":"145","timestamp":"2022-08-12 19:15:09.00 +0700","os_version":"iPhone OS 15.6 (19G71)","slice_uuid":"BA4B4090-BF8E-3993-8282-A822D1319D0C","is_first_party":1,"build_version":"","incident_id":"CD45A2D5-E58D-4A82-944F-258647E4D998","app_name":"aggregated","name":"aggregated"}
Date/Time:        2022-08-12 13:23:53.115 +0700
End time:         2022-08-12 19:15:07.782 +0700
OS Version:       iPhone OS 15.6 (Build 19G71)
Architecture:     arm64e
Report Version:   35.1
Incident Identifier: CD45A2D5-E58D-4A82-944F-258647E4D998
