### ISSUE TITLE
Error loading lua [string ":lua"]:168: '=' expected near '<eof>'

### ISSUE THREAD

**Issue by nappalm** [craftzdog/dotfiles-public#21]
I am new this. 
When I copy your xp configuration it throws me the following error in windows.
That I have to do?

![image](https://user-images.githubusercontent.com/35016608/139553906-a3b9a5d8-a86d-4cda-8b59-94c6b14c2ccd.png)

**Comment by nuo-promise** [comment]
It's probably due to the inconsistency of the line break at the end of windows and mac @nappalm

**Comment by rv-nath** [comment]
Doesn't work for me.  I tried a simple script in junk.lua
```
return redis.call("ping")
```

When I load the script in redis-cli, I get the same error.  I tried unix2dos, dos2unix etc., but nothing works! I am struggling over this for the past 2 hours without any success.
