### ISSUE TITLE
Font not showing some characters

### ISSUE THREAD

**Issue by Giuliopime** [craftzdog/dotfiles-public#26]
Hi just a quick question, I'm unable to get some characters with the Hack font, is there a specific version I should get, currently I got it from here --> https://github.com/source-foundry/Hack#macos

This is what I'm seeing atm
![Screenshot 2021-11-22 at 15 50 50](https://user-images.githubusercontent.com/60524738/142882606-b7bc13a8-01d4-4941-bc74-243de707986e.png)

**Comment by craftzdog** [comment]
Read the README

**Comment by Giuliopime** [comment]
Could you be more specific?
