### ISSUE TITLE
Telescope's `file_browser` doesn't work anymore

### ISSUE THREAD

**Issue by fisenkodv** [craftzdog/dotfiles-public#36]
As per https://github.com/nvim-telescope/telescope.nvim/pull/1453 the `builtin.file_browser` moves  into its own extension: https://github.com/nvim-telescope/telescope-file-browser.nvim.

Please refer to the following line https://github.com/craftzdog/dotfiles-public/blob/bce13abf5f307328e511bef9c8fd88cb37c1e934/.config/nvim/after/plugin/telescope.rc.vim#L5

**Comment by mPanasiewicz** [comment]
You're right.

Basically for navigation there is different plugin
https://github.com/craftzdog/dotfiles-public/blob/master/.config/nvim/plug.vim#L14

**Comment by mPanasiewicz** [comment]
Exactly, I think the same. To confirm your suggestion it raises an error when `;b`
![image](https://user-images.githubusercontent.com/9081428/163407743-a8c880a0-5c5a-4286-9cb0-648ed28d570e.png)

**Comment by fisenkodv** [comment]
@mPanasiewicz correct

**Comment by fisenkodv** [comment]
Added `;b` map to https://github.com/nvim-telescope/telescope-file-browser.nvim to my `dotfiles` repository https://github.com/fisenkodv/dotfiles/commit/7a391086ad8698ad4a8b03a97169095bc8238c48 it looks nice btw.

**Comment by craftzdog** [comment]
Good point. I haven't been using `;b` but `defx.nvim` instead these days. I'll remove that.
