### ISSUE TITLE
vim.lsp.diagnostic.show_line_diagnostics is deprecated

### ISSUE THREAD

**Issue by eisukeesaki** [craftzdog/dotfiles-public#39]
When using the [the nvim configs](https://github.com/craftzdog/dotfiles-public/tree/d940233ec2efbeee2ee5b5b82f6793ab7a4bd123/.config/nvim) on [neovim 0.7.0](https://github.com/neovim/neovim/tree/v0.7.0), nvim throws the following error:
`vim.lsp.diagnostic.show_line_diagnostics is deprecated. See :h deprecated`

I followed [the neovim documentation](https://neovim.io/doc/user/deprecated.html) and changed [the following line](https://github.com/craftzdog/dotfiles-public/blob/d940233ec2efbeee2ee5b5b82f6793ab7a4bd123/.config/nvim/after/plugin/lspconfig.rc.vim#L38)
`buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)`
 to
`buf_set_keymap('n', '<space>e', '<cmd>lua vim.diagnostic.open_float()<CR>', opts)`
and now the error is not thrown, but no diagnostics are shown when pressing the corresponding keymap.
From the [the neovim documentation](https://neovim.io/doc/user/deprecated.html) I followed a link to the documentation for `vim.diagnostic.open_float()` but the link seems to be broken right now, and I could not find useful information else where nor figure out a fix by myself.

**Comment by craftzdog** [comment]
Use [lspsaga](https://github.com/glepnir/lspsaga.nvim#jump-diagnostic-and-show-diagnostics) instead
