### ISSUE TITLE
Tabline in vim not showing up

### ISSUE THREAD

**Issue by sudipghimire533** [craftzdog/dotfiles-public#4]
Hey! I tried to setup tabline using your function but still nothing is shown. I am also using lualine. Any help?

**Comment by horsemandotpy** [comment]
Did you open file in new buffer or new tab ? 
Buffer.
![image](https://user-images.githubusercontent.com/50260408/167278979-f32d37d4-4b99-44a5-819d-6116ccfcc9f5.png)
Open in tab using tabedit command.
![image](https://user-images.githubusercontent.com/50260408/167279020-96ab7f14-05b0-4984-b8e3-642028768243.png)
