### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by maxmx03** [craftzdog/dotfiles-public#45]
## Suggestions

Hello Takuya, how are you?
This is my suggestion to improve your workflow, I see you use format in save right?
Well, you don't always need to format right? sometimes you just need to save, why not disable format on save and enable autosave and create new keymap to format.

example:

lspconfig.lua
```lua
local function on_attach(client, bufnr)
  local bufopts = { noremap = true, silent = true, buffer = bufnr }

 vim.keymap.set('n', '<space>l', vim.lsp.buf.format, bufopts)

 vim.api.nvim_create_autocmd({ 'InsertLeave', 'TextChanged' }, {
   buffer = bufnr,
   command = 'update',
 })
end
```
looking forward to your new videos.

**Comment by craftzdog** [comment]
I have a command to disable the autocmd https://github.com/craftzdog/dotfiles-public/blob/master/.config/nvim/plugin/null-ls.rc.lua#L37
