### ISSUE TITLE
suggestion: spell checker

### ISSUE THREAD

**Issue by fisenkodv** [craftzdog/dotfiles-public#53]
Thank you for the amazing `.files` and especially the `nvim` configuration. I think it would be nice to have a spell checker configuration too, e.g. https://github.com/lewis6991/spellsitter.nvim

I've added spell checker in my repository https://github.com/fisenkodv/dotfiles/commit/f7f3c451ea9fad8ca001a44db9dfe562df2c2d6b

If you like the idea, please let me know and I'll create a PR.

**Comment by fixbullshit14** [comment]
hi i am fik 
maybe u can help me ? 
i have no idea about this : 

"message":{"Count":2,"activeSMSUser":0,"activeTreatments":"100:210304_control,101:210415_control,102:210304_control,103:210304_control,105:210304_control,106:210304_control,107:210304_control,104:210304_control,108:210601_control,109:20419_control","activeiMessageUser":0,"automaticSharingEnabled":2,"musicAutomaticSharing":true,"newsAutomaticSharing":false,"photosAutomaticSharing":true,"podcastsAutomaticSharing":true,"safariAutomaticSharing":true,"tvAutomaticSharing":true},"name":"SocialHighlights_SettingsStatus_v1_boolean","sampling":100,"uuid":"02d92ea8-f2aa-4de8-a215-8251d53c3a55_2"}

**Comment by fisenkodv** [comment]
@fixbullshit14I I have no idea what are you talking about...

**Comment by fixbullshit14** [comment]
i am realy blind about code
would u please help me

**Comment by fixbullshit14** [comment]
share_with_app_devs":0,"app_version":"","bug_type":"145","timestamp":"2022-08-12 19:15:09.00 +0700","os_version":"iPhone OS 15.6 (19G71)","slice_uuid":"BA4B4090-BF8E-3993-8282-A822D1319D0C","is_first_party":1,"build_version":"","incident_id":"CD45A2D5-E58D-4A82-944F-258647E4D998","app_name":"aggregated","name":"aggregated"}
Date/Time:        2022-08-12 13:23:53.115 +0700
End time:         2022-08-12 19:15:07.782 +0700
OS Version:       iPhone OS 15.6 (Build 19G71)
Architecture:     arm64e
Report Version:   35.1
Incident Identifier: CD45A2D5-E58D-4A82-944F-258647E4D998

**Comment by fisenkodv** [comment]
@fixbullshit14 your issue is not related to spell check and this repository.

**Comment by craftzdog** [comment]
no, I'm not planning to add spell checker
