### ISSUE TITLE
Is markdown-preview.nvim support macbook m2 air?

### ISSUE THREAD

**Issue by CollieIsCute** [craftzdog/dotfiles-public#60]
I found a issue (https://github.com/iamcco/markdown-preview.nvim/issues/490) , and I guess it's caused by arm.

Does @craftzdog met the same issue on macbook air m2? If you could give me a Yes/No answer, that will be very useful! Thank you very much!

**Comment by Microctar** [comment]
Hello, @CollieIsCute

You can try to modify the build script of package.json of  [iamcco/markdown-preview](https://github.com/iamcco/markdown-preview.nvim
).

See https://github.com/vercel/pkg#targets for more details.

**Comment by CollieIsCute** [comment]
@Microctar Thanks! This suolution looks great! I just wanted to try this method, and found that the previous issue fixed itself with no reason. haha! thanks a lot!!
