### ISSUE TITLE
I have been able to fix several problems, however even the nvim is not 100%,

### ISSUE THREAD

**Issue by MrShortcut** [craftzdog/dotfiles-public#61]
I have been able to fix several problems, however even the nvim is not 100%,
- I was able to fix lsp to detect the syntax.... -> TSinstall html css javascript,
- I was able to fix guibg -> bg errors.... -> modify lua file configs.
- lsp finder not working 100%
- prettier autoformatter doesn't work in any of my environments.

tested on windows 11 and ubuntu WSL.

check my fixes and more mappings.

https://github.com/MrShortcut/nvim

**Comment by remy-poirier** [comment]
I also have trouble with Prettier not being run when saving, however the `:Prettier` command works fine.
Did you manage to get it working ?

**Comment by remy-poirier** [comment]
ok finally I thank I make it worked by "simply" adding this line to my `null_ls.rc.lua` (into sources)

```
null_ls.builtins.formatting.prettier
```

**Comment by bfulop** [comment]
@remy-poirier, would you mind sharing that part of your setup,  that runs `null_ls.builtins.formatting.prettier` on save? 🙏 

I still cannot get it working, I'm still not very fluent with lsp configurations..

Thanks!

**Comment by remy-poirier** [comment]
I'm really not fluent with lsp at all, to be honest I didn't knew anything about this language before yesterday, when I watched Takuya's video.

I will share you some of my files:

**after/plugin/prettier.rc.lua**
```
local prettier = require("prettier")

prettier.setup({
  bin = 'prettierd', -- or `'prettierd'` (v0.22+)
  filetypes = {
    "css",
    "graphql",
    "html",
    "javascript",
    "javascriptreact",
    "json",
    "less",
    "markdown",
    "scss",
    "typescript",
    "typescriptreact",
    "yaml",
  }
})
```

**plugin/null-ls.rc.lua**

```
local status, null_ls = pcall(require, "null-ls")
if (not status) then return end

local augroup_format = vim.api.nvim_create_augroup("Format", { clear = true })

null_ls.setup {
  sources = {
    null_ls.builtins.diagnostics.eslint_d.with({
      diagnostics_format = '[eslint] #{m}\n(#{c})'
    }),
    null_ls.builtins.diagnostics.fish,
    null_ls.builtins.formatting.stylua.with({ filetypes = { "lua" } }),
    null_ls.builtins.formatting.prettier
  },
  on_attach = function(client, bufnr)
    if client.server_capabilities.documentFormattingProvider then
      vim.api.nvim_clear_autocmds { buffer = 0, group = augroup_format }
      vim.api.nvim_create_autocmd("BufWritePre", {
        group = augroup_format,
        buffer = 0,
        callback = function() vim.lsp.buf.formatting_seq_sync(nil, 10000) end
      })
    end
  end
}
```

I hope this helped you

**Comment by bfulop** [comment]
Thank you @remy-poirier for sharing your setup!
I added it to my config and it seems to work well, Prettier is now used to format my files on save!
