### ISSUE TITLE
No highlights in HTML

### ISSUE THREAD

**Issue by gmmoose20** [craftzdog/dotfiles-public#81]
Did you have problems with html highlights after updating nvim-treesitter??

**Comment by CofCat456** [comment]
try to change highlight in treesitter.rc.lua to hightlight and it can work for me  😀

**Comment by CofCat456** [comment]
try to highlight.enable = false，spite that listen so weird，but that method truley solution my problem

**Comment by apicgg** [comment]
Yes, I have faced the same issue. The neosolarized theme seems not be working.

**Comment by apicgg** [comment]
<img width="1325" alt="Screenshot 2022-10-25 at 9 54 32 PM" src="https://user-images.githubusercontent.com/78271602/197829935-7e9f86e3-6b7c-47c0-81a6-44876573d9ef.png">

This is how the html file looks like.

**Comment by apicgg** [comment]
@gmmoose20 In this case you need to use older version of treesitter. Go to your plugins.lua and replace the nvim-treesitter with the below.

	-- treesitter configuration
	use({
		"nvim-treesitter/nvim-treesitter",
		commit = "8e763332b7bf7b3a426fd8707b7f5aa85823a5ac",
		run = function()
			require("nvim-treesitter.install").update({ with_sync = true })
		end,
	})

This will fix the issue.

**Comment by gmmoose20** [comment]
@apicgg Great!! 

I fixed the issue too but in different method I added these code inside neosolarized.rc.lua 

```
Group.new("@tag", colors.green)
Group.new("@tag.attribute", colors.blue)
Group.new("@tag.delimiter", colors.red)
```

with this you don't have to revert back and use older version of treesitter :)

**Comment by apicgg** [comment]
> 

Nice. Thanks for the suggestion. But in this case the highlights are not working for tsx or jsx files in my case. But anyway thanks again.

**Comment by apicgg** [comment]
> > > 
> > 
> > 
> > Nice. Thanks for the suggestion. But in this case the highlights are not working for tsx or jsx files in my case. But anyway thanks again.
> 
> @apicgg sorry forgot to edit, you need to do `:TSUpdate` after

Done. Working again. Thanks a lot!! :)

**Comment by fedpre** [comment]
I lost the highlights in the top part of any .astro file. Did anyone has the same issue? Solutions? The one presented before fixed the HTML tags but not that one.
Thanks!
![Screenshot 2022-11-02 at 16 40 51](https://user-images.githubusercontent.com/82700080/199534315-5884e4c2-d259-4067-b26c-8ff6072437f4.png)

**Comment by apicgg** [comment]
> I lost the highlights in the top part of any .astro file. Did anyone has the same issue? Solutions? The one presented before fixed the HTML tags but not that one. Thanks! ![Screenshot 2022-11-02 at 16 40 51](https://user-images.githubusercontent.com/82700080/199534315-5884e4c2-d259-4067-b26c-8ff6072437f4.png)

For the issue with .astro, I am really not sure about that right away. Let me take look into that if i can find anything. For temp workaround you can downgrade the treesitter version and give it a try if it's working.

Add the below inside your lua file where plugins are mentioned. Instead of using the latest treesitter, it will use the mentioned commit of the plugins.

```
-- treesitter configuration
use({
	"nvim-treesitter/nvim-treesitter",
	commit = "8e763332b7bf7b3a426fd8707b7f5aa85823a5ac",
	run = function()
		require("nvim-treesitter.install").update({ with_sync = true })
	end,
})
```

**Comment by fedpre** [comment]
> > I lost the highlights in the top part of any .astro file. Did anyone has the same issue? Solutions? The one presented before fixed the HTML tags but not that one. Thanks! ![Screenshot 2022-11-02 at 16 40 51](https://user-images.githubusercontent.com/82700080/199534315-5884e4c2-d259-4067-b26c-8ff6072437f4.png)
> 
> For the issue with .astro, I am really not sure about that right away. Let me take look into that if i can find anything. For temp workaround you can downgrade the treesitter version and give it a try if it's working.
> 
> Add the below inside your lua file where plugins are mentioned. Instead of using the latest treesitter, it will use the mentioned commit of the plugins.
> 
> ```
> -- treesitter configuration
> use({
> 	"nvim-treesitter/nvim-treesitter",
> 	commit = "8e763332b7bf7b3a426fd8707b7f5aa85823a5ac",
> 	run = function()
> 		require("nvim-treesitter.install").update({ with_sync = true })
> 	end,
> })
> ```

Thanks apicgg! I will take a look at it and see to downgrade it. I really hope we can find a better solution like the one gmmoose20 that fixed the issue of HTML very nicely. Is there a group or something similar for the jsxor tsx syntax in .astro files?

**Comment by gmmoose20** [comment]
> > > I lost the highlights in the top part of any .astro file. Did anyone has the same issue? Solutions? The one presented before fixed the HTML tags but not that one. Thanks! ![Screenshot 2022-11-02 at 16 40 51](https://user-images.githubusercontent.com/82700080/199534315-5884e4c2-d259-4067-b26c-8ff6072437f4.png)
> > 
> > 
> > For the issue with .astro, I am really not sure about that right away. Let me take look into that if i can find anything. For temp workaround you can downgrade the treesitter version and give it a try if it's working.
> > Add the below inside your lua file where plugins are mentioned. Instead of using the latest treesitter, it will use the mentioned commit of the plugins.
> > ```
> > -- treesitter configuration
> > use({
> > 	"nvim-treesitter/nvim-treesitter",
> > 	commit = "8e763332b7bf7b3a426fd8707b7f5aa85823a5ac",
> > 	run = function()
> > 		require("nvim-treesitter.install").update({ with_sync = true })
> > 	end,
> > })
> > ```
> 
> Thanks apicgg! I will take a look at it and see to downgrade it. I really hope we can find a better solution like the one gmmoose20 that fixed the issue of HTML very nicely. Is there a group or something similar for the jsxor tsx syntax in .astro files?

try  `:TSInstall astro`  :)

**Comment by fedpre** [comment]
> > > > I lost the highlights in the top part of any .astro file. Did anyone has the same issue? Solutions? The one presented before fixed the HTML tags but not that one. Thanks! ![Screenshot 2022-11-02 at 16 40 51](https://user-images.githubusercontent.com/82700080/199534315-5884e4c2-d259-4067-b26c-8ff6072437f4.png)
> > > 
> > > 
> > > For the issue with .astro, I am really not sure about that right away. Let me take look into that if i can find anything. For temp workaround you can downgrade the treesitter version and give it a try if it's working.
> > > Add the below inside your lua file where plugins are mentioned. Instead of using the latest treesitter, it will use the mentioned commit of the plugins.
> > > ```
> > > -- treesitter configuration
> > > use({
> > > 	"nvim-treesitter/nvim-treesitter",
> > > 	commit = "8e763332b7bf7b3a426fd8707b7f5aa85823a5ac",
> > > 	run = function()
> > > 		require("nvim-treesitter.install").update({ with_sync = true })
> > > 	end,
> > > })
> > > ```
> > 
> > 
> > Thanks apicgg! I will take a look at it and see to downgrade it. I really hope we can find a better solution like the one gmmoose20 that fixed the issue of HTML very nicely. Is there a group or something similar for the jsxor tsx syntax in .astro files?
> 
> try `:TSInstall astro` :)

Thanks for your reply! I did add astro to my configuration for the treesitter, but I still didn't get the highlights :(

**Comment by gmmoose20** [comment]
hmm thats weird, its working fine on my end after `:TSInstall astro`
![image](https://user-images.githubusercontent.com/62541303/199689845-eaa22574-9124-4554-8b84-db85d051e800.png)

**Comment by fedpre** [comment]
> hmm thats weird, its working fine on my end after `:TSInstall astro` ![image](https://user-images.githubusercontent.com/62541303/199689845-eaa22574-9124-4554-8b84-db85d051e800.png)

Found the problem. I didn't have typescript installed in my treesitter. I feel stupid haha thanks for the help now it works perfectly!

**Comment by gmmoose20** [comment]
> > hmm thats weird, its working fine on my end after `:TSInstall astro` ![image](https://user-images.githubusercontent.com/62541303/199689845-eaa22574-9124-4554-8b84-db85d051e800.png)
> 
> Found the problem. I didn't have typescript installed in my treesitter. I feel stupid haha thanks for the help now it works perfectly!

great!! :) 🙌

**Comment by craftzdog** [comment]
Thanks for the quick fix, @gmmoose20
It's been merged into the theme
https://github.com/svrana/neosolarized.nvim/pull/7
