### ISSUE TITLE
cannot use command  ide tmux

### ISSUE THREAD

**Issue by fiqryq** [craftzdog/dotfiles-public#83]
Hi takuya , i use your dotfile for my neovim env and thats help me a lot thankyou so much!.  i need help , i cant use command ```ide``` on my tmux can you help me for this issue?

**Comment by oasido** [comment]
You'll need to create a script file for it, store it in a path like `/opt/` (name the file `ide`) or any other custom path to your liking. Then edit your `.bashrc` or `.zshrc` if you're using `zsh` to update the `PATH` accordingly, so the command `ide` will work.

**Comment by 1337deniz** [comment]
How can i create this script file ?

**Comment by oasido** [comment]
@1337deniz This is the one I use
```
#!/bin/bash
tmux neww -n 'app'
tmux split-window -v -p 50
tmux neww -n 'git'
tmux select-window -t:1
```
