### ISSUE TITLE
What is your omf theme?

### ISSUE THREAD

**Issue by nuo-promise** [craftzdog/dotfiles-public#9]

**Comment by nuo-promise** [comment]
~/.config/fish/functions/_tide_prompt.fish (line 49):
        _tide_item_$item
        ^
in function '_tide_right_prompt'
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 2 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
fish: Unknown command: _tide_item_rust
~/.config/fish/functions/_tide_prompt.fish (line 49):
        _tide_item_$item
        ^
in function '_tide_right_prompt'
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 2 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'



I used the tide theme and got this error after configuration

**Comment by nuo-promise** [comment]
resloved!

**Comment by craftzdog** [comment]
👍
