### ISSUE TITLE
format on save doesn't work

### ISSUE THREAD

**Issue by lili21** [craftzdog/dotfiles-public#92]
[this commit](https://github.com/craftzdog/dotfiles-public/commit/940ed444f911fb2a3c1592734de16721095b7510) delete the `prettier.rc.lua` file. which maybe the reason.

I put the file back, and now it works.

**Comment by Pkcarreno** [comment]
I'm experiencing something similar to @lili21, but in my case is that neither prettier nor eslint format when saving (or assigning it to any key).
I have a couple of weeks like this, before everything was ok, so I assume it was the fault of some plugin that was updated but I can't find which one.

**Comment by AlvaroAquijeDiaz** [comment]
Same issue here, anyone found workarounds?

**Comment by Pkcarreno** [comment]
Hey @AlvaroAquijeDiaz and @lili21, you both are on windows? Take a look at this [https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1118](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1118)

**Comment by AlvaroAquijeDiaz** [comment]
> Hey @AlvaroAquijeDiaz and @lili21, you both are on windows? Take a look at this [https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1118](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1118)

I'm on macOS but will check as well and update if found some workaround

**Comment by Pkcarreno** [comment]
@AlvaroAquijeDiaz, There is an error in null-ls regarding the path of the language server executable, specifically those coming from npm.

However I managed to solve my eslint problem by adding `null_ls.builtins.formatting.eslint_d` inside sources of the null-ls configuration as below:

```lua
null_ls.setup {
  sources = {
    null_ls.builtins.formatting.prettierd,
    null_ls.builtins.formatting.eslint_d, -- Here
    null_ls.builtins.diagnostics.eslint_d.with({
      diagnostics_format = '[eslint] #{m}\n(#{c})'
    }),
    null_ls.builtins.diagnostics.fish
  },
  ...
}
```

I hope it helps you

**Comment by AlvaroAquijeDiaz** [comment]
@Pkcarreno great news, I haven't had the chance to look at the other link you mentioned but will update when I do it

**Comment by DindoLeonard** [comment]
In the null-ls.rc.lua, just rewrite `null_ls.builtins.formatting.prettierd` -> `null_ls.builtins.formatting.prettier`. worked for me

```lua
-- inside null.ls.setup()
  sources = {
    null_ls.builtins.formatting.prettier,
    -- null_ls.builtins.diagnostics.eslint_d.with({
    --   diagnostics_format = '[eslint] #{m}\n(#{c})'
    -- }),
    null_ls.builtins.diagnostics.zsh,
    null_ls.builtins.diagnostics.eslint_d.with({ -- js/ts linter
      -- only enable eslint if root has .eslintrc.js (not in youtube nvim video)
      condition = function(utils)
        return utils.root_has_file(".eslintrc.js") -- change file extension if you use something else
      end,
    }),
    null_ls.builtins.code_actions.eslint_d
  },

```
