### ISSUE TITLE
Copy And Paste to clipboard not working on windows 11 

### ISSUE THREAD

**Issue by harshv1741** [craftzdog/dotfiles-public#98]
![image](https://user-images.githubusercontent.com/51878195/215309600-a54a190d-61f0-4902-80ea-df1e72d71863.png)

##Problem
---
When I upgraded my PC from windows 10 to windows 11. The above screenshot shows daily, I tried to google about it but still not found the answer for it. Copy and paste to clipboard function is also not working. If someone is facing similar issue please help me regarding this problem.

**Comment by utbrott** [comment]
I've looked into your configuration. Your `init.lua` on L14 has `require(windows)`.
Neovim while loading looks for a file `windows.lua` in the same directory as the init file.
Change the code to `require(default.windows)` (cause that's the path to the actual `windows.lua` file you have in the config) and your issue shoud get resolved.
