### ISSUE TITLE
Tmux

### ISSUE THREAD

**Issue by haruops** [craftzdog/dotfiles-public#99]
Hi all. I have a problem with **tmux**.
Windows change the name to the name of the directory I'm in.
How to fix it? Thx

![telegram-cloud-photo-size-2-5397962761184592975-x](https://user-images.githubusercontent.com/44260786/216670941-cc3a456d-4227-45a5-bae8-e6dd4dc034c6.jpg)

**Comment by igniscyan** [comment]
I assume you mean you don't want tmux to automatically rename?

This line should be in your tmux.conf,`set-option -g automatic-rename off` However, this should be the default setting. Make sure you didn't copy over this option from another conf.

**Comment by haruops** [comment]
Yes, I want tmux not to automatically windows rename. 
All default tmux settings.

https://user-images.githubusercontent.com/44260786/219677213-28c4b255-fa3c-46f0-b1bb-ee9e7b539b36.mp4
